### ISSUE TITLE
Proof of Concept: Developing a Custom Theme Without Monorepo

### ISSUE THREAD

**Issue by zelal-dev** [js-template/padma#74]
## Description  
I am preparing a proof of concept for developing a custom theme without using a monorepo setup.  

The goal is for users to run the following command:  
```bash
npx padma create my-project
```  
This will start a new project with a selected theme.  

## Current Challenge  
We currently do not have any themes available. Therefore, I am working on creating a guide to help users develop their own custom themes.  

## To-Do  
- [x] Prepare a detailed guide for custom theme development.  
- [x] Outline steps to integrate a theme into the project.  
- [x] Test the proof of concept to ensure usability.  

## Additional Notes  
This is an initial exploration, and feedback or suggestions are welcome!
